#!/bin/sh
# Run simulation and save the log in buoy.log file
buoyantBoussinesqPvapFoam > buoy.log
# Create liquid temperature profiles
postProcess -func singleGraph

#------------------------------------------------------------------------------
