#!/bin/sh
cd ${0%/*} || exit 1                        # Run from this directory
. $WM_PROJECT_DIR/bin/tools/CleanFunctions  # Tutorial clean functions

rm -r [1-9]*
rm -r proc*
rm -r postProcessing
rm buoy.log
#------------------------------------------------------------------------------
